### ISSUE TITLE
IOS resource for modern jailbreak 

### ISSUE THREAD

**Issue by ahmedrowaihi** [Malaa-tech/root-jailbreak-detection-expo#1]
Malaa Team,
I love you efforts..

here is my little resource I would love to share for IOS

the [UIDevice.swift](https://github.com/Malaa-tech/root-jailbreak-detection-expo/blob/main/ios/UIDevice.swift) looks good, and here is more [FilesPathToCheck.swift](https://github.com/SachinSabat/CheckJailBreakDevice/blob/master/CheckJailBreakDevice/FilesPathToCheck.swift) along with similar techs for detections

Best regards champs :'D

**Comment by AlfayezDev** [comment]
Will try to add whenever possible, thank you for the recommendations.
